inputs:
  ref_prompt: "A `cat wearing wearable `glasses in a watercolor style."
  base_prompt: "A `cat wearing wearable `glasses in a watercolor style."
  negative_prompt: ""
  custom_prompts:
    - "A <gray_cat_1> `<gray_cat_2> wearing wearable <gray_cat_1> `<gray_cat_2> in a watercolor style."
    - "A <glasses_1> `<glasses_2> wearing wearable <glasses_1> `<glasses_2> in a watercolor style."

  ref_image_path: "examples/cat_wearing_glasses/cat_wearing_glasses.png"
  ref_mask_paths:
    - "examples/cat_wearing_glasses/mask_cat.png"
    - "examples/cat_wearing_glasses/mask_glasses.png" 
  init_mask_from_points: False
  mask_center_points: 
    - [250, 250]
    - [250, 250]
    - [250, 250]
  init_image_path: ~
  init_mask_path: ~       
  edlora_paths: 
    - "ed-loras/gray_cat.pth"  
    - "ed-loras/glasses.pth"  
  load_edlora: True
  lora_alpha: 0.7

outputs:
  outroot: "outputs/p4"
  image_outdir: "inference_results"
  latents_outdir: "inverted_latents"
  self_attn_outdir: "self_attn"
  cross_attn_outdir: "cross_attn"
  feature_mask_outdir: "feature_mask"


base_model:
  sd_ckpt: "pretrained_models/anything-v4.0"
  variant: ""

sd_t2i:
  height: 512
  width: 512
  guidance_scale: 7.5
  num_inference_steps: 200
  start_seed: 0
  batch_size: 2
  n_batches: 2
  verbose: False

attention_operations:
  attn_guidance_end: 60
  attn_guidance_interval: 1
  attn_guidance_weight: 10
  custom_attn_guidance_factor: 1.0

  processor_filter_guidance: '.*up_blocks\.1\.attentions\.0.*attn1.*'
  params_guidance: ["key"]
  processor_filter_mask: '.*up_blocks\.2\.attentions\.2.*attn1.*'
  params_mask: ['attention_probs']
  processor_filter_merge: '.*up_blocks.*'
  params_merge: ["feature_output"]
  processor_filter_view_sa: '.*up_blocks\.2\.attentions\.2.*attn1.*'
  params_view_sa: ["attention_probs"]      
  processor_filter_view_ca: '.*up_blocks\.2\.attentions\.1.*attn2.*'
  params_view_ca: ["attention_probs"]    

  mask_refinement_start: 50
  mask_refinement_end: 80
  mask_update_interval: 5
  mask_overlap_threshold: 0
  num_kmeans_init: 100
  rect_mask: False

  use_loss_mask: False
  visualization: False



